<?php
include 'commom.php';
$total_amount=$_SESSION['price'];
?>
<script src="https://code.jquery.com/jquery-3.5.0.js">

</script>
<form action="success.php" method="POST">
    <script
        src="https://checkout.razorpay.com/v1/checkout.js"
        data-key="rzp_test_ceQXrIOlYTHTPJ" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
        data-amount="<?php echo $total_amount*100 ;?>" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
        data-currency="INR"// You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
        data-order_id="<?php 'OID'.rand(10,100).'END'?>"// Replace with the order_id generated by you in the backend.
        data-buttontext="Pay with Razorpay"
        data-name="Hypertext Assasins PVT LTD"
        data-description="Testing Phase"
        data-image="websiteimages/logo.jpg"
        data-prefill.name="<?php echo $_SESSION['name'] ?>"
        data-prefill.email="<?php echo $_SESSION['email'] ?>"
        data-theme.color="#F37254"
    ></script>
    <input type="hidden" custom="Hidden Element" name="hidden">
    </form>

<style>
     .razorpay-payment-button {display : none;}
</style>
        <script type="text/javascript">
        $(window).on('load', function(){
            $('.razorpay-payment-button').click();
        });
        </script>

